FROM ubuntu:14.04
MAINTAINER chris@dragonfly.co.nz

# use New Zealand mirrors and set timezone to Auckland

RUN sed -i 's/archive/nz.archive/' /etc/apt/sources.list
RUN echo "Pacific/Auckland" > /etc/timezone
RUN dpkg-reconfigure -f noninteractive tzdata

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN locale-gen en_NZ.UTF-8
RUN dpkg-reconfigure locales

ENV LANG en_NZ.UTF-8
ENV LANGUAGE en_NZ:en

__INCLUDE_DF_USER__

